# Generated by Django 3.2.8 on 2021-12-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_bid',
            new_name='bid',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='bid_listing',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='bid_by_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_by_user',
            new_name='by_user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_listing',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(default='no_photo.png', upload_to='images'),
        ),
    ]
