# Generated by Django 3.2.8 on 2021-12-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20211202_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
